apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dvwa-deployment
  namespace: bachelor-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dvwa
    spec:
      containers:
      - name: dvwa-container
        image: vulnerables/web-dvwa
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-service
  labels:
    name: dvwa-service
  namespace: bachelor-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31337
  selector:
    name: dvwa