(function(g){var window=this;var Opa=function(a,b){return g.Ub(a,b)},G2=function(){},Ppa=function(a){if(a.Ac&&"function"==typeof a.Ac)return a.Ac();
if(g.Da(a))return a.split("");if(g.La(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Qb(a)},Qpa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.La(a)||g.Da(a))(0,g.y)(a,b,void 0);else{if(a.Od&&"function"==typeof a.Od)var c=a.Od();else if(a.Ac&&"function"==typeof a.Ac)c=void 0;else if(g.La(a)||g.Da(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Rb(a);d=Ppa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},H2=function(a){g.sn(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.D)()).toString(36));
return a},I2=function(a,b,c){g.Ka(c)||(c=[String(c)]);
g.xn(a.l,b,c)},J2=function(a){return(a=g.Qo(a))?new ActiveXObject(a):new XMLHttpRequest},K2=function(a,b){return b+" ["+a.Z+" "+a.D+" "+a.getStatus()+"]"},Rpa=function(a){return"content-type"==a.toLowerCase()},L2=function(a){a.g&&a.I&&(a.g.ontimeout=null);
a.F&&(g.u.clearTimeout(a.F),a.F=null)},Spa=function(a){return g.Ld&&g.ld(9)&&g.Fa(a.timeout)&&g.Ca(a.ontimeout)},M2=function(a){a.P||(a.P=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},N2=function(a,b){if(a.g){L2(a);
var c=a.g,d=a.R[0]?g.Ha:null;a.g=null;a.R=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},O2=function(a,b){a.i=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.l=b;a.u=5;M2(a);N2(a)},P2=function(a){return a.g?a.g.readyState:0},Q2=function(a){if(a.i&&"undefined"!=typeof g.FV)if(a.R[1]&&4==P2(a)&&2==a.getStatus())K2(a,"Local request error detected and ignored");
else if(a.B&&4==P2(a))g.Gg(a.Ew,0,a);else if(a.dispatchEvent("readystatechange"),4==P2(a)){K2(a,"Request complete");a.i=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(1,String(a.D));if(!f&&g.u.self&&g.u.self.location){var k=g.u.self.location.protocol;f=k.substr(0,k.length-1)}e=!Tpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.u=6;try{var l=2<P2(a)?a.g.statusText:""}catch(m){l=""}a.l=l+" ["+a.getStatus()+"]";M2(a)}}finally{N2(a)}}},R2=function(a){g.Sf.call(this);
this.headers=new g.gn;this.M=a||null;this.i=!1;this.R=this.g=null;this.Z=this.D="";this.u=0;this.l="";this.o=this.ba=this.B=this.P=!1;this.A=0;this.F=null;this.X="";this.I=this.T=!1},S2=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Upa=function(a,b){var c=[];
g.Pk(b,function(d){try{var e=g.ep.prototype.i.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.Ca(e)?g.dp(e)&&c.push(d):c.push(d)},a);
return c},Vpa=function(a,b){var c=Upa(a,b);
(0,g.y)(c,function(d){g.ep.prototype.remove.call(this,d)},a)},T2=function(a){if(a.gd){if(a.gd.locationOverrideToken)return{locationOverrideToken:a.gd.locationOverrideToken};
if(null!=a.gd.latitudeE7&&null!=a.gd.longitudeE7)return{latitudeE7:a.gd.latitudeE7,longitudeE7:a.gd.longitudeE7}}return null},Wpa=function(a,b){g.$a(a,b)||a.push(b)},U2=function(a){var b=0,c;
for(c in a)b++;return b},V2=function(a,b){var c=b instanceof g.xc?b:g.Dc(b,/^data:image\//i.test(b));
a.src=g.yc(c)},Xpa=function(a){try{return g.u.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Ypa=function(a,b,c,d){var e=new g.kn(null,void 0);
a&&g.ln(e,a);b&&g.mn(e,b);c&&g.nn(e,c);d&&(e.i=d);return e},W2=function(a){if(g.u.JSON)try{return g.u.JSON.parse(a)}catch(b){}return Xpa(a)},X2=function(){this.g=[];
this.i=[]},Y2=function(a,b){g.jq[a]=!0;
var c=g.hq();c&&c.publish.apply(c,arguments);g.jq[a]=!1},Z2=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.l=!1;this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.gn;this.g=this.i="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Zpa(this,a.capabilities||""),$pa(this,a.experiments||""),this.i=a.remoteControllerUrl||"",this.g=a.localChannelEncryptionKey||
"")},Zpa=function(a,b){a.capabilities.clear();
(0,g.Xd)(b.split(","),g.Qa(Opa,aqa)).forEach(function(c){a.capabilities.add(c)})},$pa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},$2=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},a3=function(a,b){return!!b&&(a.id==b||a.uuid==b)},b3=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},bqa=function(a){return new $2(a)},c3=function(a){return g.Ka(a)?(0,g.ge)(a,bqa):[]},d3=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},e3=function(a){return g.Ka(a)?"["+(0,g.ge)(a,d3).join(",")+"]":"null"},f3=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},cqa=function(a){return(0,g.ge)(a,function(b){return{key:b.id,
name:b.name}})},g3=function(a,b){return g.Xa(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},h3=function(a,b){return g.Xa(a,function(c){return a3(c,b)})},i3=function(a){try{var b=(0,g.Gt)(),c=(0,g.Ft)();
b&&b.remove(a);c&&c.remove(a)}catch(d){}},dqa=function(){var a=(0,g.Ft)();
a&&Vpa(a,a.g.nf(!0))},j3=function(){var a=g.It("yt-remote-connected-devices")||[];
g.qb(a);return a},eqa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.ge)(a,function(d,e){return 0==e?d:d.substring(c.length)})},k3=function(a){g.Ht("yt-remote-connected-devices",a,86400)},m3=function(){if(l3)return l3;
var a=g.It("yt-remote-device-id");a||(a=f3(),g.Ht("yt-remote-device-id",a,31536E3));for(var b=j3(),c=1,d=a;g.$a(b,d);)c++,d=a+"#"+c;return l3=d},n3=function(){var a=j3(),b=m3();
g.$a(a,b);g.Jt()&&g.sb(a,b);a=eqa(a);if(0==a.length)try{g.Ks("remote_sid")}catch(c){}else try{g.Js("remote_sid",a.join(","),-1)}catch(c){}},o3=function(){return g.It("yt-remote-session-browser-channel")},p3=function(){return g.It("yt-remote-local-screens")||[]},q3=function(){g.Ht("yt-remote-lounge-token-expiration",!0,86400)},fqa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.ge)(p3(),function(d){return d.loungeToken}),c=(0,g.ge)(a,function(d){return d.loungeToken});
(0,g.kj)(c,function(d){return!g.$a(b,d)})&&q3();
g.Ht("yt-remote-local-screens",a,31536E3)},gqa=function(a,b){g.Ht("yt-remote-session-browser-channel",a);
g.Ht("yt-remote-session-screen-id",b);var c=j3(),d=m3();g.$a(c,d)||c.push(d);k3(c);n3()},r3=function(a){a||(i3("yt-remote-session-screen-id"),i3("yt-remote-session-video-id"));
n3();a=j3();g.db(a,m3());k3(a)},t3=function(){if(!s3){var a=g.op();
a&&(s3=new g.Zo(a))}return s3?!!s3.get("yt-remote-use-staging-server"):!1},u3=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},v3=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},x3=function(a){a.length?w3(a.shift(),function(){x3(a)}):y3()},hqa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},w3=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},y3=function(){var a=v3();
a&&a(!1,"No cast extension found")},z3=function(){if(iqa){var a=2,b=v3(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;w3("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",y3,c)}},jqa=function(){z3();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);x3(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},A3=function(a,b,c){g.A.call(this);
this.A=null!=c?(0,g.x)(a,c):a;this.Yc=b;this.u=(0,g.x)(this.ED,this);this.g=!1;this.i=0;this.l=this.Aa=null;this.o=[]},B3=function(){},C3=function(a,b,c,d){this.g=a;
this.l=b;this.B=c;this.A=d||1;this.o=45E3;this.ca=new g.yn(this);this.i=new g.Fg;this.i.setInterval(250)},E3=function(a,b,c){a.Xh=1;
a.Zf=H2(b.clone());a.qh=c;a.u=!0;D3(a,null)},F3=function(a,b,c,d,e){a.Xh=1;
a.Zf=H2(b.clone());a.qh=null;a.u=c;e&&(a.vA=!1);D3(a,d)},D3=function(a,b){a.Gi=(0,g.D)();
G3(a);a.Eg=a.Zf.clone();I2(a.Eg,"t",a.A);a.nl=0;a.uc=a.g.Vp(a.g.Vk()?b:null);0<a.Dq&&(a.co=new g.Hl((0,g.x)(a.CB,a,a.uc),a.Dq));a.ca.da(a.uc,"readystatechange",a.tM);var c=a.Xg?g.bc(a.Xg):{};a.qh?(a.Mo="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.uc.send(a.Eg,a.Mo,a.qh,c)):(a.Mo="GET",a.vA&&!g.Nd&&(c.Connection="close"),a.uc.send(a.Eg,a.Mo,null,c));a.g.Ce(1)},N3=function(a,b,c){for(var d=!0;!a.Ng&&a.nl<c.length;){var e=kqa(a,c);
if(e==H3){4==b&&(a.rg=4,I3(15),d=!1);break}else if(e==J3){a.rg=4;I3(16);d=!1;break}else K3(a,e)}4==b&&0==c.length&&(a.rg=1,I3(17),d=!1);a.Fe=a.Fe&&d;d||(L3(a),M3(a))},kqa=function(a,b){var c=a.nl,d=b.indexOf("\n",c);
if(-1==d)return H3;c=Number(b.substring(c,d));if(isNaN(c))return J3;d+=1;if(d+c>b.length)return H3;var e=b.substr(d,c);a.nl=d+c;return e},Q3=function(a,b){a.Gi=(0,g.D)();
G3(a);var c=b?window.location.hostname:"";a.Eg=a.Zf.clone();g.sn(a.Eg,"DOMAIN",c);g.sn(a.Eg,"t",a.A);try{a.Ie=new ActiveXObject("htmlfile")}catch(n){L3(a);a.rg=7;I3(22);M3(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in O3)k=O3[l];else if(l in P3)k=O3[l]=P3[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
O3[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Rc(g.qc("b/12014412"),d+"</body></html>");a.Ie.open();a.Ie.write(g.Mc(c));a.Ie.close();a.Ie.parentWindow.m=(0,g.x)(a.IL,a);a.Ie.parentWindow.d=(0,g.x)(a.Cz,a,!0);a.Ie.parentWindow.rpcClose=(0,g.x)(a.Cz,a,!1);c=a.Ie.createElement("DIV");a.Ie.parentWindow.document.body.appendChild(c);d=g.Cc(a.Eg.toString());d=g.Yc(g.zc(d));d=g.Rc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Sc(c,d);a.g.Ce(1)},G3=function(a){a.Jt=(0,g.D)()+a.o;
R3(a,a.o)},R3=function(a,b){if(null!=a.Xi)throw Error("WatchDog timer not null");
a.Xi=S3((0,g.x)(a.SL,a),b)},T3=function(a){a.Xi&&(g.u.clearTimeout(a.Xi),a.Xi=null)},M3=function(a){a.g.Cw()||a.Ng||a.g.On(a)},L3=function(a){T3(a);
g.qf(a.co);a.co=null;a.i.stop();g.An(a.ca);if(a.uc){var b=a.uc;a.uc=null;b.abort();b.dispose()}a.Ie&&(a.Ie=null)},K3=function(a,b){try{a.g.wz(a,b),a.g.Ce(4)}catch(c){}},V3=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;U3(a,b,function(k){k?c(!0):g.u.setTimeout(function(){V3(a,b,c,d,f)},f)})}},U3=function(a,b,c){var d=new Image;
d.onload=function(){try{W3(d),c(!0)}catch(e){}};
d.onerror=function(){try{W3(d),c(!1)}catch(e){}};
d.onabort=function(){try{W3(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{W3(d),c(!1)}catch(e){}};
g.u.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
V2(d,a)},W3=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},X3=function(a){this.g=a;
this.i=new B3},Z3=function(a){var b=Y3(a.g,a.mj,"/mail/images/cleardot.gif");
H2(b);V3(b.toString(),5E3,(0,g.x)(a.LC,a),3,2E3);a.Ce(1)},a4=function(a){var b=a.g.F;
if(null!=b)I3(5),b?(I3(11),$3(a.g,a,!1)):(I3(12),$3(a.g,a,!0));else if(a.Hd=new C3(a,void 0,void 0,void 0),a.Hd.Xg=a.Bq,b=a.g,b=Y3(b,b.Vk()?a.Tj:null,a.Cq),I3(5),!g.Ld||g.md(10))I2(b,"TYPE","xmlhttp"),F3(a.Hd,b,!1,a.Tj,!1);else{I2(b,"TYPE","html");var c=a.Hd;a=!!a.Tj;c.Xh=3;c.Zf=H2(b.clone());Q3(c,a)}},b4=function(a,b,c){this.g=1;
this.i=[];this.o=[];this.u=new B3;this.D=a||null;this.F=null!=b?b:null;this.A=c||!1},lqa=function(a,b){this.g=a;
this.map=b;this.context=null},c4=function(a){g.sf.call(this,"statevent",a)},d4=function(a,b){g.sf.call(this,"timingevent",a);
this.size=b},e4=function(a){g.sf.call(this,"serverreachability",a)},i4=function(a){f4(a);
if(3==a.g){var b=a.Ck++,c=a.pm.clone();g.sn(c,"SID",a.l);g.sn(c,"RID",b);g.sn(c,"TYPE","terminate");g4(a,c);b=new C3(a,a.l,b,void 0);b.Xh=2;b.Zf=H2(c.clone());V2(new Image,b.Zf.toString());b.Gi=(0,g.D)();G3(b)}h4(a)},k4=function(a){a.eD(1,0);
a.pm=Y3(a,null,a.Aq);j4(a)},f4=function(a){a.hg&&(a.hg.abort(),a.hg=null);
a.Ub&&(a.Ub.cancel(),a.Ub=null);a.qf&&(g.u.clearTimeout(a.qf),a.qf=null);l4(a);a.Ed&&(a.Ed.cancel(),a.Ed=null);a.og&&(g.u.clearTimeout(a.og),a.og=null)},m4=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.i.push(new lqa(a.WH++,b));2!=a.g&&3!=a.g||j4(a)},j4=function(a){a.Ed||a.og||(a.og=S3((0,g.x)(a.Bz,a),0),a.Qh=0)},p4=function(a,b){if(1==a.g){if(!b){a.Ck=Math.floor(1E5*Math.random());
var c=a.Ck++,d=new C3(a,"",c,void 0);d.Xg=null;var e=n4(a),f=a.pm.clone();g.sn(f,"RID",c);g.sn(f,"CVER","1");g4(a,f);E3(d,f,e);a.Ed=d;a.g=2}}else 3==a.g&&(b?o4(a,b):0==a.i.length||a.Ed||o4(a))},o4=function(a,b){if(b)if(6<a.Og){a.i=a.o.concat(a.i);
a.o.length=0;var c=a.Ck-1;var d=n4(a)}else c=b.B,d=b.qh;else c=a.Ck++,d=n4(a);var e=a.pm.clone();g.sn(e,"SID",a.l);g.sn(e,"RID",c);g.sn(e,"AID",a.ji);g4(a,e);c=new C3(a,a.l,c,a.Qh+1);c.Xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Ed=c;E3(c,e,d)},g4=function(a,b){if(a.Vc){var c=a.Vc.bw();
c&&g.Kb(c,function(d,e){g.sn(b,e,d)})}},n4=function(a){var b=Math.min(a.i.length,1E3),c=["count="+b];
if(6<a.Og&&0<b){var d=a.i[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.i[e].g,k=a.i[e].map;f=6>=a.Og?e:f-d;try{g.Kb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.o=a.o.concat(a.i.splice(0,b));
return c.join("&")},q4=function(a){a.Ub||a.qf||(a.B=1,a.qf=S3((0,g.x)(a.Az,a),0),a.Jh=0)},s4=function(a){if(a.Ub||a.qf||3<=a.Jh)return!1;
a.B++;a.qf=S3((0,g.x)(a.Az,a),r4(a,a.Jh));a.Jh++;return!0},$3=function(a,b,c){a.Ko=c;
a.Ne=b.Af;a.A||k4(a)},l4=function(a){null!=a.Sg&&(g.u.clearTimeout(a.Sg),a.Sg=null)},r4=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},u4=function(a,b){if(2==b||9==b){var c=null;
a.Vc&&(c=null);var d=(0,g.x)(a.ZM,a);c||(c=new g.kn("//www.google.com/images/cleardot.gif"),H2(c));U3(c.toString(),1E4,d)}else I3(2);t4(a,b)},t4=function(a,b){a.g=0;
a.Vc&&a.Vc.cv(b);h4(a);f4(a)},h4=function(a){a.g=0;
a.Ne=-1;if(a.Vc)if(0==a.o.length&&0==a.i.length)a.Vc.Jp();else{g.gb(a.o);var b=g.gb(a.i);a.o.length=0;a.i.length=0;a.Vc.Jp(b)}},Y3=function(a,b,c){var d=g.tn(c);
if(""!=d.g)b&&g.mn(d,b+"."+d.g),g.nn(d,d.u);else{var e=window.location;d=Ypa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.Bj&&g.Kb(a.Bj,function(f,k){g.sn(d,k,f)});
g.sn(d,"VER",a.Og);g4(a,d);return d},S3=function(a,b){if(!g.Ma(a))throw Error("Fn must not be null and must be a function");
return g.u.setTimeout(function(){a()},b)},I3=function(a){v4.dispatchEvent(new c4(v4,a))},w4=function(){},mqa=function(a,b){this.action=a;
this.params=b||{}},x4=function(a,b){g.A.call(this);
this.g=new g.J(this.AL,0,this);g.B(this,this.g);this.Yc=5E3;this.i=0;if(g.Ma(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Ma(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.l=a},y4=function(a,b,c){this.H=a;
this.A=b;this.l=new g.Yo;this.i=new x4(this.DM,this);this.g=null;this.ib=!1;this.u=null;this.F="";this.D=this.o=0;this.B=[];this.I=c||!1},nqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ko,sessionId:a.g.l,arrayId:a.g.ji}},z4=function(a,b){a.D=b||0;
a.i.stop();a.g&&(3==a.g.g&&p4(a.g),i4(a.g));a.D=0},A4=function(a){return!!a.g&&3==a.g.g},oqa=function(a,b){(a.A.loungeIdToken=b)||a.i.stop()},B4=function(a){this.port=this.domain="";
this.g="/api/lounge";this.i=!0;a=a||document.location.href;var b=Number(g.Sg(4,a))||"";b&&(this.port=":"+b);this.domain=g.Tg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Hb(a,"10.0")&&(this.i=!1))},C4=function(a,b){var c=a.g;
if(g.Ca(void 0)?0:a.i)c="https://"+a.domain+a.port+a.g;return g.$g(c+b,{})},D4=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Qa(a.o,d,!0),onError:g.Qa(a.l,e),oe:g.Qa(a.u,e)};c&&(a.wb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.br(b,a)},pqa=function(){var a=E4;
F4();G4.push(a);H4(G4)},I4=function(a,b){F4();
var c=G4,d=qqa(a,String(b));0==c.length?rqa(d):(H4(c),(0,g.y)(c,function(e){e(d)}))},F4=function(){G4||(G4=g.w("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",G4,void 0))},rqa=function(a){var b=(J4+1)%50;
J4=b;K4[b]=a;L4||(L4=49==b)},H4=function(a){var b=K4;
if(b[0]){var c=J4,d=L4?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
K4=Array(50);J4=-1;L4=!1}},qqa=function(a,b){var c=((0,g.D)()-sqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},M4=function(a){g.N.call(this);
this.B=a;this.g=[]},N4=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},tqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Xd)(a.g,function(f){return!!g3(b,f)});
for(var d=0,e=b.length;d<e;d++)c=N4(a,b[d])||c;return c},uqa=function(a,b){var c=a.g.length;
a.g=(0,g.Xd)(a.g,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.g.length<c},O4=function(a,b,c,d){g.N.call(this);
this.A=a;this.u=b;this.l=c;this.o=d;this.i=0;this.g=null;this.Aa=NaN},Q4=function(a){M4.call(this,"LocalScreenService");
this.l=a;this.i=NaN;P4(this);this.info("Initializing with "+e3(this.g))},R4=function(a){if(a.g.length){var b=(0,g.ge)(a.g,function(d){return d.id}),c=C4(a.l,"/pairing/get_lounge_token_batch");
D4(a.l,c,{screen_ids:b.join(",")},(0,g.x)(a.OD,a),(0,g.x)(a.ND,a))}},P4=function(a){var b=c3(p3());
b=(0,g.Xd)(b,function(c){return!c.uuid});
return tqa(a,b)},S4=function(a,b){fqa((0,g.ge)(a.g,b3));
b&&q3()},U4=function(a,b){g.N.call(this);
this.A=b;var c=g.It("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.A(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.$a(c,l)}this.g=d;this.u=a;this.l=this.o=NaN;this.i=null;T4("Initialized with "+g.Kg(this.g))},V4=function(a,b,c){var d=C4(a.u,"/pairing/get_screen_availability");
D4(a.u,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},W4=function(a,b){a:if(U2(b)!=U2(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(T4("Updated online screens: "+g.Kg(a.g)),a.g=b,a.N("screenChange"));vqa(a)},X4=function(a){isNaN(a.l)||g.gq(a.l);
a.l=g.eq((0,g.x)(a.Ns,a),0<a.o&&a.o<(0,g.D)()?2E4:1E4)},T4=function(a){I4("OnlineScreenService",a)},Y4=function(a){var b={};
(0,g.y)(a.A(),function(c){c.token?b[c.token]=c.id:this.Gb("Requesting availability of screen w/o lounge token.")});
return b},vqa=function(a){a=g.Rb(g.Lb(a.g,function(b){return b}));
g.qb(a);a.length?g.Ht("yt-remote-online-screen-ids",a.join(","),60):i3("yt-remote-online-screen-ids")},Z4=function(a){M4.call(this,"ScreenService");
this.A=a;this.i=this.l=null;this.o=[];this.u={};wqa(this)},a5=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.u[b]);var k=a.Qd();if(k=(c?h3(k,c):null)||h3(k,b)){k.uuid=b;var l=$4(a,k);V4(a.i,l,function(m){e(m?l:null)})}else c?xqa(a,c,(0,g.x)(function(m){var n=$4(this,new $2({name:d,
screenId:c,loungeToken:m,dialId:b||""}));V4(this.i,n,function(p){e(p?n:null)})},a),f):e(null)},b5=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},xqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={wb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.br(C4(a.A,"/pairing/get_lounge_token_batch"),e)},c5=function(a){a.g=a.l.Qd();
var b=a.u,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+e3(a.g))},wqa=function(a){d5(a);
a.l=new Q4(a.A);a.l.subscribe("screenChange",(0,g.x)(a.WD,a));c5(a);a.o=c3(g.It("yt-remote-automatic-screen-cache")||[]);d5(a);a.info("Initializing automatic screens: "+e3(a.o));a.i=new U4(a.A,(0,g.x)(a.Qd,a,!0));a.i.subscribe("screenChange",(0,g.x)(function(){this.N("onlineScreenChange")},a))},$4=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=h3(a.o,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.o.push(b),g.Ht("yt-remote-automatic-screen-cache",(0,g.ge)(a.o,b3)));d5(a);a.u[b.uuid]=b.id;g.Ht("yt-remote-device-id-map",a.u,31536E3);return b},d5=function(a){a.u=g.It("yt-remote-device-id-map")||{}},e5=function(a,b,c){g.N.call(this);
this.R=c;this.F=a;this.i=b;this.l=null},f5=function(a,b){I4(a.R,b)},h5=function(a,b){e5.call(this,a,b,"CastSession");
this.g=null;this.o=0;this.A=(0,g.x)(this.EN,this);this.u=(0,g.x)(this.dM,this);this.o=g.eq((0,g.x)(function(){g5(this,null)},this),12E4)},yqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ha,(0,g.x)(function(){f5(this,"Failed to send message: getMdxSessionStatus.")},a)):f5(a,"Sending yt message without session: "+g.Kg(b))},g5=function(a,b){g.gq(a.o);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.l||a.l.id!=b){var c=(0,g.x)(a.Qn,a),d=(0,g.x)(a.Td,a);a.tw(b,c,d,5)}}else a.Td(Error("Waiting for session status timed out."))},i5=function(a,b,c){e5.call(this,a,b,"DialSession");
this.o=this.D=null;this.H="";this.M=c;this.u=null;this.B=g.Ha;this.A=NaN;this.I=(0,g.x)(this.HN,this);this.g=g.Ha},j5=function(a){a.g=a.F.HB(a.H,a.i.label,a.i.friendlyName,(0,g.x)(function(b){this.g=g.Ha;
this.Qn(b)},a),(0,g.x)(function(b){this.g=g.Ha;
this.Td(b)},a))},k5=function(a){var b={};
b.pairingCode=a.H;b.theme=a.M;if(a.u){var c=a.u.currentTime||0;b.v=a.u.videoId;b.t=c}t3()&&(b.env_useStageMdx=1);return g.Zg(b)},l5=function(a,b){e5.call(this,a,b,"ManualSession");
this.g=g.eq((0,g.x)(this.li,this,null),150)},m5=function(a,b,c,d){g.N.call(this);
this.i=a;this.B=b||"233637DE";this.A=c||"cl";this.D=d||!1;this.g=null;this.u=!1;this.l=[];this.o=(0,g.x)(this.IK,this)},n5=function(a,b){return b?g.Xa(a.l,function(c){return a3(b,c.label)},a):null},o5=function(a){I4("Controller",a)},E4=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},p5=function(a){return a.u||!!a.l.length||!!a.g},q5=function(a,b,c){b!=a.g&&(g.qf(a.g),(a.g=b)?(c?a.N("yt-remote-cast2-receiver-resumed",b.i):a.N("yt-remote-cast2-receiver-selected",
b.i),b.subscribe("sessionScreen",(0,g.x)(a.zz,a,b)),b.l?a.N("yt-remote-cast2-session-change",b.l):c&&a.g.li(null)):a.N("yt-remote-cast2-session-change",null))},r5=function(a){var b=a.i.GB(),c=a.g&&a.g.i;
a=(0,g.ge)(b,function(d){c&&a3(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=n5(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Cqa=function(a,b,c,d,e,f,k){zqa()?Aqa(b,e,f,k)&&(t5(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?u5(a,c):(window.__onGCastApiAvailable=function(l,m){l?u5(a,c):(v5("Failed to load cast API: "+m),w5(!1),t5(!1),i3("yt-remote-cast-available"),i3("yt-remote-cast-receiver"),x5(),c(!1))},d?g.rq("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?jqa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?y3():(z3(),x3(Bqa.map(hqa))))):s5("Cannot initialize because not running Chrome")},x5=function(){s5("dispose");
var a=y5();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);z5(!1);g.mq(A5);A5.length=0},B5=function(){return!!g.It("yt-remote-cast-installed")},C5=function(){var a=g.It("yt-remote-cast-receiver");
return a?a.friendlyName:null},D5=function(){s5("clearCurrentReceiver");
i3("yt-remote-cast-receiver")},E5=function(){return B5()?y5()?y5().getCastSession():(v5("getCastSelector: Cast is not initialized."),null):(v5("getCastSelector: Cast API is not installed!"),null)},G5=function(){B5()?y5()?F5()?(s5("Requesting cast selector."),y5().requestSession()):(s5("Wait for cast API to be ready to request the session."),A5.push(g.lq("yt-remote-cast2-api-ready",G5))):v5("requestCastSelector: Cast is not initialized."):v5("requestCastSelector: Cast API is not installed!")},H5=function(a,
b){F5()?y5().setConnectedScreenStatus(a,b):v5("setConnectedScreenStatus called before ready.")},zqa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.qx||a},Dqa=function(a,b){y5().init(a,b)},Aqa=function(a,b,c,d){var e=!1;
y5()||(a=new m5(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Ht("yt-remote-cast-available",f);Y2("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){s5("onReceiverSelected: "+f.friendlyName);
g.Ht("yt-remote-cast-receiver",f);Y2("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){s5("onReceiverResumed: "+f.friendlyName);
g.Ht("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){s5("onSessionChange: "+d3(f));
f||i3("yt-remote-cast-receiver");Y2("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
s5("cloudview.createSingleton_: "+e);return e},y5=function(){return g.w("yt.mdx.remote.cloudview.instance_")},u5=function(a,b){w5(!0);
t5(!1);Dqa(a,function(c){c?(z5(!0),g.oq("yt-remote-cast2-api-ready")):(v5("Failed to initialize cast API."),w5(!1),i3("yt-remote-cast-available"),i3("yt-remote-cast-receiver"),x5());b(c)})},s5=function(a){I4("cloudview",a)},v5=function(a){I4("cloudview",a)},w5=function(a){s5("setCastInstalled_ "+a);
g.Ht("yt-remote-cast-installed",a)},F5=function(){return!!g.w("yt.mdx.remote.cloudview.apiReady_")},z5=function(a){s5("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},t5=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},I5=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.A=this.B=0;this.g=null;this.hasNext=this.Oe=!1;this.F=this.D=this.i=this.o=0;this.l=NaN;this.u=!1;this.reset(a)},J5=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Oe=!1;a.hasNext=!1;a.B=0;a.A=(0,g.D)();a.o=0;a.i=0;a.D=0;a.F=0;a.l=NaN;a.u=!1},K5=function(a){return 1==a.playerState?((0,g.D)()-a.A)/1E3:0},L5=function(a,b){a.B=b;
a.A=(0,g.D)()},M5=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.A)/1E3+a.B;
case -1E3:return 0}return a.B},N5=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J5(a)},O5=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.cc(a.g);b.hasPrevious=a.Oe;b.hasNext=a.hasNext;b.playerTime=a.B;b.playerTimeAt=a.A;b.seekableStart=a.o;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.F;b.liveIngestionTime=a.l;return b},R5=function(a,b){g.N.call(this);
this.g=0;this.o=a;this.A=[];this.u=new X2;this.l=this.i=null;this.F=(0,g.x)(this.FI,this);this.B=(0,g.x)(this.Ek,this);this.D=(0,g.x)(this.DI,this);this.H=(0,g.x)(this.TI,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Mt,this),P5(this))):c=3;0!=c&&(b?this.Mt(c):g.eq((0,g.x)(function(){this.Mt(c)},this),0));
var d=E5();d&&Q5(this,d);this.subscribe("yt-remote-cast2-session-change",this.H)},S5=function(a){return new I5(a.o.getPlayerContextData())},P5=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.A.push(this.o.subscribe(b,g.Qa(this.FK,b),this))},a)},T5=function(a){(0,g.y)(a.A,function(b){this.o.unsubscribeByKey(b)},a);
a.A.length=0},U5=function(a,b){var c=a.u;
50>c.g.length+c.i.length&&a.u.i.push(b)},W5=function(a,b,c){var d=S5(a);
L5(d,c);-1E3!=d.playerState&&(d.playerState=b);V5(a,d)},X5=function(a,b,c){a.o.sendMessage(b,c)},V5=function(a,b){T5(a);
a.o.setPlayerContextData(O5(b));P5(a)},Q5=function(a,b){a.l&&(a.l.removeUpdateListener(a.F),a.l.removeMediaListener(a.B),a.Ek(null));
a.l=b;a.l&&(I4("CP","Setting cast session: "+a.l.sessionId),a.l.addUpdateListener(a.F),a.l.addMediaListener(a.B),a.l.media.length&&a.Ek(a.l.media[0]))},Y5=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=S5(a);b.contentId!=d.videoId&&I4("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L5(d,a.i.getEstimatedTime());V5(a,d)}else I4("CP","No cast media video. Ignoring state update.")},Z5=function(a,b,c){return(0,g.x)(function(d){this.Gb("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.Gb("Retrying "+b+" using MDx browser channel."),X5(this,b,c))},a)},$5=function(a,b,c){g.N.call(this);
this.u=NaN;this.I=!1;this.D=this.B=this.F=this.H=NaN;this.R=[];this.o=this.A=this.l=this.Pa=this.g=null;this.P=a;this.R.push(g.ks(window,"beforeunload",(0,g.x)(this.HD,this)));this.i=[];this.Pa=new I5;this.M=b.id;this.g=Eqa(this,c);this.g.subscribe("handlerOpened",this.JI,this);this.g.subscribe("handlerClosed",this.GI,this);this.g.subscribe("handlerError",this.HI,this);this.g.subscribe("handlerMessage",this.II,this);oqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var d=this.Pa.videoId;
g.Jt()&&g.Ht("yt-remote-session-video-id",d)},this)},a6=function(a){I4("conn",a)},Eqa=function(a,b){return new y4(C4(a.P,"/bc"),b)},b6=function(a,b){a.N("proxyStateChange",b)},Fqa=function(a){a.u=g.eq((0,g.x)(function(){a6("Connecting timeout");
this.Nh(1)},a),2E4)},c6=function(a){g.gq(a.u);
a.u=NaN},d6=function(a){g.gq(a.H);
a.H=NaN},Gqa=function(a){e6(a);
a.F=g.eq((0,g.x)(function(){f6(this,"getNowPlaying")},a),2E4)},e6=function(a){g.gq(a.F);
a.F=NaN},h6=function(a,b){b&&(c6(a),d6(a));
b==(A4(a.g)&&isNaN(a.u))?b&&(b6(a,1),f6(a,"getSubtitlesTrack")):b?(a.qw()&&a.Pa.reset(),b6(a,1),f6(a,"getNowPlaying"),g6(a)):a.Nh(1)},Hqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Pa.videoId&&(g.Xb(b.params)?a.Pa.g=null:a.Pa.g=b.params,a.N("remotePlayerChange"))},i6=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.Pa.listId=b.params.listId||a.Pa.listId;N5(a.Pa,c,d);a.N("remoteQueueChange")},Iqa=function(a,b){b.params=b.params||{};
i6(a,b);j6(a,b);a.N("autoplayDismissed")},j6=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L5(a.Pa,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.Pa.playerState&&(c=-1E3);a.Pa.playerState=c;c=Number(b.params.loadedTime);a.Pa.F=isNaN(c)?0:c;c=Number(b.params.duration);a.Pa.D=isNaN(c)?0:c;c=a.Pa;var d=Number(b.params.liveIngestionTime);c.l=d;c.u=isNaN(d)?!1:!0;c=a.Pa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.o=isNaN(d)?0:d;c.i=isNaN(e)?0:e;1==a.Pa.playerState?Gqa(a):e6(a);a.N("remotePlayerChange")},Jqa=function(a,b){if(-1E3!=
a.Pa.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Pa.playerState=c;c=parseInt(b.params.currentTime,10);L5(a.Pa,isNaN(c)?0:c);a.N("remotePlayerChange")}},Kqa=function(a,b){var c="true"==b.params.muted;
a.Pa.volume=parseInt(b.params.volume,10);a.Pa.muted=c;a.N("remotePlayerChange")},Lqa=function(a,b){a.A=b.params.videoId;
a.N("nowAutoplaying",parseInt(b.params.timeout,10))},Mqa=function(a,b){var c="true"==b.params.hasNext;
a.Pa.Oe="true"==b.params.hasPrevious;a.Pa.hasNext=c;a.N("previousNextChange")},g6=function(a){g.gq(a.D);
a.D=g.eq((0,g.x)(a.Nh,a,1),864E5)},f6=function(a,b,c){c?a6("Sending: action="+b+", params="+g.Kg(c)):a6("Sending: action="+b);
a.g.sendMessage(b,c)},k6=function(a){M4.call(this,"ScreenServiceProxy");
this.Xc=a;this.i=[];this.i.push(this.Xc.$_s("screenChange",(0,g.x)(this.CN,this)));this.i.push(this.Xc.$_s("onlineScreenChange",(0,g.x)(this.kK,this)))},Rqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.Xp("MDX_CONFIG")||b;dqa();n3();l6||(l6=new B4(b?b.loungeApiHost:void 0),t3()&&(l6.g="/api/loungedev"));m6||(m6=g.w("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",m6,void 0));Nqa();var c=n6();if(!c){var d=new Z4(l6);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=n6();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Cqa(a,d,function(m){m?o6()&&H5(o6(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){Y2("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.w("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),p6("Initializing: "+g.Kg(b)),q6.push(g.lq("yt-remote-cast2-availability-change",function(){Y2("yt-remote-receiver-availability-change")})),q6.push(g.lq("yt-remote-cast2-receiver-selected",function(){r6(null);
Y2("yt-remote-auto-connect","cast-selector-receiver")})),q6.push(g.lq("yt-remote-cast2-receiver-resumed",function(){Y2("yt-remote-receiver-resumed","cast-selector-receiver")})),q6.push(g.lq("yt-remote-cast2-session-change",Oqa)),q6.push(g.lq("yt-remote-connection-change",function(m){m?H5(o6(),"YouTube TV"):s6()||(H5(null,null),D5())})),a=t6(),b.isAuto&&(a.id+="#dial"),g.Tq("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),p6(" -- with channel params: "+
g.Kg(a)),Pqa(a),c.start(),o6()||Qqa())},Sqa=function(){var a=u6();
B5()&&g.It("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},u6=function(){var a=n6().Xc.$_gos();
var b=v6();b&&w6()&&(g3(a,b)||a.push(b));return cqa(a)},x6=function(){var a=Tqa();
!a&&B5()&&C5()&&(a={key:"cast-selector-receiver",name:C5()});return a},Tqa=function(){var a=u6(),b=v6();
b||(b=s6());return g.Xa(a,function(c){return b&&a3(b,c.key)?!0:!1})},v6=function(){var a=o6();
if(!a)return null;var b=n6().Qd();return h3(b,a)},Oqa=function(a){p6("remote.onCastSessionChange_: "+d3(a));
if(a){var b=v6();b&&b.id==a.id?H5(b.id,"YouTube TV"):(b&&y6(),z6(a,1))}else w6()&&y6()},y6=function(){F5()?y5().stopSession():v5("stopSession called before API ready.");
var a=w6();a&&(a.disconnect(1),A6(null))},B6=function(){var a=w6();
return!!a&&3!=a.getProxyState()},p6=function(a){I4("remote",a)},n6=function(){if(!C6){var a=g.w("yt.mdx.remote.screenService_");
C6=a?new k6(a):null}return C6},o6=function(){return g.w("yt.mdx.remote.currentScreenId_")},D6=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},E6=function(){return g.w("yt.mdx.remote.connectData_")},r6=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},w6=function(){return g.w("yt.mdx.remote.connection_")},A6=function(a){var b=w6();
r6(null);a||D6("");g.Ga("yt.mdx.remote.connection_",a,void 0);m6&&((0,g.y)(m6,function(c){c(a)}),m6.length=0);
b&&!a?Y2("yt-remote-connection-change",!1):!b&&a&&Y2("yt-remote-connection-change",!0)},s6=function(){var a=g.Jt();
if(!a)return null;var b=n6().Qd();return h3(b,a)},z6=function(a,b){v6()&&v6();
if(F6)G6=a;else{D6(a.id);var c=new $5(l6,a,t6());c.connect(b,E6());c.subscribe("beforeDisconnect",function(d){Y2("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){w6()&&A6(null)});
A6(c)}},Qqa=function(){var a=s6();
a?(p6("Resume connection to: "+d3(a)),z6(a,0)):(r3(),D5(),p6("Skipping connecting because no session screen found."))},Nqa=function(){var a=t6();
if(g.Xb(a)){a=m3();var b=g.It("yt-remote-session-name")||"",c=g.It("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},t6=function(){return g.w("yt.mdx.remote.channelParams_")||{}},Pqa=function(a){a?(g.Ht("yt-remote-session-app",a.app),g.Ht("yt-remote-session-name",a.name)):(i3("yt-remote-session-app"),i3("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},H6=function(a,b,c){g.A.call(this);
this.u=a;this.i=b;this.l=new g.Us(this);g.B(this,this.l);this.l.K(b,"onCaptionsTrackListChanged",this.FJ);this.l.K(b,"captionschanged",this.CI);this.l.K(b,"captionssettingschanged",this.UA);this.l.K(b,"videoplayerreset",this.Rn);this.l.K(b,"mdxautoplaycancel",this.KC);this.P=this.l.K(b,"onVolumeChange",this.iz);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.vz,this);c.subscribe("remotePlayerChange",this.Gk,this);c.subscribe("remoteQueueChange",this.Rn,this);c.subscribe("autoplayUpNext",this.Wy,
this);c.subscribe("previousNextChange",this.rz,this);c.subscribe("nowAutoplaying",this.nz,this);c.subscribe("autoplayDismissed",this.Vy,this);this.suggestion=null;this.F=new g.OC(64);this.o=new g.J(this.SA,500,this);g.B(this,this.o);this.A=new g.J(this.TA,1E3,this);g.B(this,this.A);this.I=new A3(this.iN,0,this);g.B(this,this.I);this.B={};this.R=new g.J(this.uB,1E3,this);g.B(this,this.R);this.H=new g.Hl(this.cG,1E3,this);g.B(this,this.H);this.M=g.Ha;this.UA();this.Rn();this.Gk()},I6=function(a,b){a.u.td(b,
a.i.getVideoData().lengthSeconds)},K6=function(a){I6(a,0);
a.o.stop();J6(a,new g.OC(64))},M6=function(a,b){if(L6(a)&&!a.D){var c=null;
b&&(c={style:a.i.getSubtitlesUserSettings()},g.ec(c,b));a.g.JA(a.i.getVideoData(1).videoId,c);a.B=S5(a.g).g}},N6=function(a,b){var c=a.i.getPlaylist();
if(c){var d=c.Ta;var e=c.listId.toString()}c=a.i.getVideoData(1);a.g.playVideo(c.videoId,b,d,e,c.playerParams,c.Ff,T2(c));J6(a,new g.OC(1))},O6=function(a,b){if(b){var c=a.i.getOption("captions","tracklist",{fR:1});
c&&c.length?(a.i.setOption("captions","track",b),a.D=!1):(a.i.loadModule("captions"),a.D=!0)}else a.i.setOption("captions","track",{})},L6=function(a){return S5(a.g).videoId==a.i.getVideoData(1).videoId},J6=function(a,b){a.A.stop();
var c=a.F;if(!g.UC(c,b)){var d=g.T(b,2);d!=g.T(a.F,2)&&g.KK(a.i,d);a.F=b;P6(a.u,c,b)}},Q6=function(){g.V.call(this,{C:"div",
G:"ytp-mdx-popup-dialog",L:{role:"dialog"},J:[{C:"div",G:"ytp-mdx-popup-dialog-inner-content",J:[{C:"div",G:"ytp-mdx-popup-title",V:"Du bist nicht angemeldet"},{C:"div",G:"ytp-mdx-popup-description",V:"Videos, die du dir ansiehst, werden m\u00f6glicherweise zum TV-Wiedergabeverlauf hinzugef\u00fcgt und k\u00f6nnen sich damit auf deine TV-Empfehlungen auswirken. Melde dich auf einem Computer in YouTube an, um das zu vermeiden."},{C:"div",G:"ytp-mdx-privacy-popup-buttons",J:[{C:"button",W:["ytp-button",
"ytp-mdx-privacy-popup-cancel"],V:"Abbrechen"},{C:"button",W:["ytp-button","ytp-mdx-privacy-popup-confirm"],V:"Best\u00e4tigen"}]}]}]});this.l=new g.qQ(this,250);g.B(this,this.l);this.B=this.g["ytp-mdx-privacy-popup-cancel"];this.K(this.B,"click",this.o);this.u=this.g["ytp-mdx-privacy-popup-confirm"];this.K(this.u,"click",this.A)},S6=function(a){g.V.call(this,{C:"div",
G:"ytp-remote",J:[{C:"div",G:"ytp-remote-display-status",J:[{C:"div",G:"ytp-remote-display-status-icon",J:[g.RP()]},{C:"div",G:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.qQ(this,250);g.B(this,this.l);this.o=a;this.K(a,"presentingplayerstatechange",this.u);R6(this,g.GK(a))},R6=function(a,b){if(3==a.o.getPresentingPlayerType()){var c={RECEIVER_NAME:a.o.getOption("remote","currentReceiver").name};
c=g.T(b,128)?g.QN("Fehler auf $RECEIVER_NAME",c):g.VC(b)||g.T(b,4)?g.QN("Wiedergabe \u00fcber $RECEIVER_NAME",c):g.QN("Verbunden mit $RECEIVER_NAME",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},T6=function(a,b){g.bT.call(this,"Wiedergeben auf",0,a,b);
this.l=a;this.B={};this.K(a,"onMdxReceiversChange",this.I);this.K(a,"presentingplayerstatechange",this.I);this.I()},U6=function(a){g.iL.call(this,a);
this.i={key:f3(),name:"Dieser Computer"};this.u=null;this.o=[];this.F=this.g=null;this.B=[this.i];this.l=this.i;this.pk=new g.OC(64);this.I=0;this.Um=-1;if(!g.uz(g.X(this.player))){a=this.player;var b=g.HD(a);b&&(b=b.zn())&&(b=new T6(a,b),g.B(this,b));b=new S6(a);g.B(this,b);g.VK(a,b.element,4);this.H=new Q6;g.B(this,this.H);g.VK(a,this.H.element,4);this.D=!!s6()}this.A=null},V6=function(a){a.A&&(a.player.removeEventListener("presentingplayerstatechange",a.A),a.A=null)},P6=function(a,b,c){a.pk=c;
a.player.N("presentingplayerstatechange",new g.YD(c,b))},W6=function(a,b){if(b.key!=a.l.key)if(b.key==a.i.key)y6();
else{var c;if(c=g.O(g.X(a.player).experiments,"mdx_enable_privacy_disclosure_ui"))c=g.Xp("PLAYER_CONFIG"),c=!(c&&c.args&&void 0!==c.args.authuser||g.Xp("SESSION_INDEX")||g.Xp("LOGGED_IN"));c&&!a.D&&(g.VC(g.GK(a.player))||(a.A=(0,g.x)(a.kM,a),a.player.addEventListener("presentingplayerstatechange",a.A)),a.player.pauseVideo(),a.H.l.show(),w6()||(F6=!0));a.l=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(d||e){var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<
f.getLength();l++)k[l]=f.ua(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Ff,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0==f?void 0:f};(c=T2(c))&&(d.locationInfo=c);c=d}else c=null;p6("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(r6(c||null),F5()?y5().setLaunchParams(c||null):v5("setLaunchParams called before ready.")):!c&&B6()&&o6()==b.key?Y2("yt-remote-connection-change",!0):(y6(),
r6(c||null),c=n6().Qd(),(c=h3(c,b.key))&&z6(c,1))}},Tpa=/^https?$/i,Uqa=["POST",
"PUT"];g.Sa(R2,g.Sf);g.h=R2.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.D+"; newUri="+a);b=b?b.toUpperCase():"GET";this.D=a;this.l="";this.u=0;this.Z=b;this.P=!1;this.i=!0;this.g=this.M?J2(this.M):J2(g.fW);this.R=this.M?this.M.getOptions():g.fW.getOptions();this.g.onreadystatechange=(0,g.x)(this.Ew,this);try{G2(K2(this,"Opening Xhr")),this.ba=!0,this.g.open(b,String(a),!0),this.ba=!1}catch(f){G2(K2(this,"Error opening Xhr: "+f.message));O2(this,f);return}a=
c||"";var e=this.headers.clone();d&&Qpa(d,function(f,k){e.set(k,f)});
d=g.Xa(e.Od(),Rpa);c=g.u.FormData&&a instanceof g.u.FormData;!g.$a(Uqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.g.setRequestHeader(k,f)},this);
this.X&&(this.g.responseType=this.X);"withCredentials"in this.g&&this.g.withCredentials!==this.T&&(this.g.withCredentials=this.T);try{L2(this),0<this.A&&(this.I=Spa(this.g),G2(K2(this,"Will abort after "+this.A+"ms if incomplete, xhr2 "+this.I)),this.I?(this.g.timeout=this.A,this.g.ontimeout=(0,g.x)(this.Fw,this)):this.F=g.Gg(this.Fw,this.A,this)),G2(K2(this,"Sending request")),this.B=!0,this.g.send(a),this.B=!1}catch(f){G2(K2(this,"Send error: "+f.message)),O2(this,f)}};
g.h.Fw=function(){"undefined"!=typeof g.FV&&this.g&&(this.l="Timed out after "+this.A+"ms, aborting",this.u=8,K2(this,this.l),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.i&&(K2(this,"Aborting"),this.i=!1,this.o=!0,this.g.abort(),this.o=!1,this.u=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),N2(this))};
g.h.U=function(){this.g&&(this.i&&(this.i=!1,this.o=!0,this.g.abort(),this.o=!1),N2(this,!0));R2.ab.U.call(this)};
g.h.Ew=function(){this.fa()||(this.ba||this.B||this.o?Q2(this):this.HK())};
g.h.HK=function(){Q2(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<P2(this)?this.g.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return g.Da(this.l)?this.l:String(this.l)};
var P3={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},O3={"'":"\\'"},Vqa={};g.h=X2.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.i.length};
g.h.clear=function(){this.g=[];this.i=[]};
g.h.contains=function(a){return g.$a(this.g,a)||g.$a(this.i,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.zma)(b,a);0<=c?(g.bb(b,c),b=!0):b=!1;return b||g.db(this.i,a)};
g.h.Ac=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.i.length;for(b=0;b<c;++b)a.push(this.i[b]);return a};
var aqa={bO:"atp",qQ:"ska",fQ:"que",GP:"mus",pQ:"sus",XO:"dsp",mQ:"seq"};Z2.prototype.jg=function(){var a=new Z2({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.l=this.l;a.i=this.i;a.g=this.g};
var s3,l3="",iqa=u3("loadCastFramework")||u3("loadCastApplicationFramework"),Bqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.Sa(A3,g.A);g.h=A3.prototype;g.h.DD=function(a){this.o=arguments;this.g=!1;this.Aa?this.l=(0,g.D)()+this.Yc:this.Aa=g.Gg(this.u,this.Yc)};
g.h.stop=function(){this.Aa&&(g.u.clearTimeout(this.Aa),this.Aa=null);this.l=null;this.g=!1;this.o=[]};
g.h.pause=function(){++this.i};
g.h.resume=function(){this.i&&(--this.i,!this.i&&this.g&&(this.g=!1,this.A.apply(null,this.o)))};
g.h.U=function(){this.stop();A3.ab.U.call(this)};
g.h.ED=function(){this.l?(this.Aa=g.Gg(this.u,this.l-(0,g.D)()),this.l=null):(this.Aa=null,this.i?this.g=!0:(this.g=!1,this.A.apply(null,this.o)))};B3.prototype.stringify=function(a){return g.u.JSON.stringify(a,void 0)};
B3.prototype.parse=function(a){return g.u.JSON.parse(a,void 0)};g.h=C3.prototype;g.h.Xg=null;g.h.Fe=!1;g.h.Xi=null;g.h.Jt=null;g.h.Gi=null;g.h.Xh=null;g.h.Zf=null;g.h.Eg=null;g.h.qh=null;g.h.uc=null;g.h.nl=0;g.h.Ie=null;g.h.Mo=null;g.h.rg=null;g.h.Uj=-1;g.h.vA=!0;g.h.Ng=!1;g.h.Dq=0;g.h.co=null;var J3={},H3={};g.h=C3.prototype;g.h.setTimeout=function(a){this.o=a};
g.h.tM=function(a){a=a.target;var b=this.co;b&&3==P2(a)?b.Qj():this.CB(a)};
g.h.CB=function(a){try{if(a==this.uc)a:{var b=P2(this.uc),c=this.uc.u,d=this.uc.getStatus();if(g.Ld&&!g.md(10)||g.Nd&&!g.ld("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Ah&&!S2(this.uc))break a;this.Ng||4!=b||7==c||(8==c||0>=d?this.g.Ce(3):this.g.Ce(2));T3(this);var e=this.uc.getStatus();this.Uj=e;var f=S2(this.uc);(this.Fe=200==e)?(4==b&&L3(this),this.u?(N3(this,b,f),g.Ah&&this.Fe&&3==b&&(this.ca.da(this.i,"tick",this.nM),this.i.start())):K3(this,f),this.Fe&&!this.Ng&&(4==b?this.g.On(this):(this.Fe=
!1,G3(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.rg=3,I3(13)):(this.rg=0,I3(14)),L3(this),M3(this))}}catch(k){this.uc&&S2(this.uc)}finally{}};
g.h.nM=function(){var a=P2(this.uc),b=S2(this.uc);this.nl<b.length&&(T3(this),N3(this,a,b),this.Fe&&4!=a&&G3(this))};
g.h.IL=function(a){S3((0,g.x)(this.HL,this,a),0)};
g.h.HL=function(a){this.Ng||(T3(this),K3(this,a),G3(this))};
g.h.Cz=function(a){S3((0,g.x)(this.GL,this,a),0)};
g.h.GL=function(a){this.Ng||(L3(this),this.Fe=a,this.g.On(this),this.g.Ce(4))};
g.h.cancel=function(){this.Ng=!0;L3(this)};
g.h.SL=function(){this.Xi=null;var a=(0,g.D)();0<=a-this.Jt?(2!=this.Xh&&this.g.Ce(3),L3(this),this.rg=2,I3(18),M3(this)):R3(this,this.Jt-a)};
g.h.getLastError=function(){return this.rg};g.h=X3.prototype;g.h.Bq=null;g.h.Hd=null;g.h.eo=!1;g.h.Dw=null;g.h.nm=null;g.h.mr=null;g.h.Cq=null;g.h.ge=null;g.h.Af=-1;g.h.Tj=null;g.h.mj=null;g.h.connect=function(a){this.Cq=a;a=Y3(this.g,null,this.Cq);I3(3);this.Dw=(0,g.D)();var b=this.g.D;null!=b?(this.Tj=b[0],(this.mj=b[1])?(this.ge=1,Z3(this)):(this.ge=2,a4(this))):(I2(a,"MODE","init"),this.Hd=new C3(this,void 0,void 0,void 0),this.Hd.Xg=this.Bq,F3(this.Hd,a,!1,null,!0),this.ge=0)};
g.h.LC=function(a){if(a)this.ge=2,a4(this);else{I3(4);var b=this.g;b.Ne=b.hg.Af;u4(b,9)}a&&this.Ce(2)};
g.h.Vp=function(a){return this.g.Vp(a)};
g.h.abort=function(){this.Hd&&(this.Hd.cancel(),this.Hd=null);this.Af=-1};
g.h.Cw=function(){return!1};
g.h.wz=function(a,b){this.Af=a.Uj;if(0==this.ge)if(b){try{var c=this.i.parse(b)}catch(d){c=this.g;c.Ne=this.Af;u4(c,2);return}this.Tj=c[0];this.mj=c[1]}else c=this.g,c.Ne=this.Af,u4(c,2);else if(2==this.ge)if(this.eo)I3(7),this.mr=(0,g.D)();else if("11111"==b){if(I3(6),this.eo=!0,this.nm=(0,g.D)(),c=this.nm-this.Dw,!g.Ld||g.md(10)||500>c)this.Af=200,this.Hd.cancel(),I3(12),$3(this.g,this,!0)}else I3(8),this.nm=this.mr=(0,g.D)(),this.eo=!1};
g.h.On=function(){this.Af=this.Hd.Uj;if(this.Hd.Fe)0==this.ge?this.mj?(this.ge=1,Z3(this)):(this.ge=2,a4(this)):2==this.ge&&((!g.Ld||g.md(10)?!this.eo:200>this.mr-this.nm)?(I3(11),$3(this.g,this,!1)):(I3(12),$3(this.g,this,!0)));else{0==this.ge?I3(9):2==this.ge&&I3(10);var a=this.g;this.Hd.getLastError();a.Ne=this.Af;u4(a,2)}};
g.h.Vk=function(){return this.g.Vk()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Ce=function(a){this.g.Ce(a)};g.h=b4.prototype;g.h.Bj=null;g.h.Ed=null;g.h.Ub=null;g.h.Aq=null;g.h.pm=null;g.h.Qu=null;g.h.Dm=null;g.h.Ck=0;g.h.WH=0;g.h.Vc=null;g.h.og=null;g.h.qf=null;g.h.Sg=null;g.h.hg=null;g.h.Ko=null;g.h.ji=-1;g.h.nx=-1;g.h.Ne=-1;g.h.Qh=0;g.h.Jh=0;g.h.Og=8;var v4=new g.Sf;g.Sa(c4,g.sf);g.Sa(d4,g.sf);g.Sa(e4,g.sf);g.h=b4.prototype;g.h.connect=function(a,b,c,d,e){I3(0);this.Aq=b;this.Bj=c||{};d&&g.Ca(e)&&(this.Bj.OSID=d,this.Bj.OAID=e);this.A?(S3((0,g.x)(this.lv,this,a),100),k4(this)):this.lv(a)};
g.h.lv=function(a){this.hg=new X3(this);this.hg.Bq=null;this.hg.i=this.u;this.hg.connect(a)};
g.h.Cw=function(){return 0==this.g};
g.h.Bz=function(a){this.og=null;p4(this,a)};
g.h.Az=function(){this.qf=null;this.Ub=new C3(this,this.l,"rpc",this.B);this.Ub.Xg=null;this.Ub.Dq=0;var a=this.Qu.clone();g.sn(a,"RID","rpc");g.sn(a,"SID",this.l);g.sn(a,"CI",this.Ko?"0":"1");g.sn(a,"AID",this.ji);g4(this,a);if(!g.Ld||g.md(10))g.sn(a,"TYPE","xmlhttp"),F3(this.Ub,a,!0,this.Dm,!1);else{g.sn(a,"TYPE","html");var b=this.Ub,c=!!this.Dm;b.Xh=3;b.Zf=H2(a.clone());Q3(b,c)}};
g.h.wz=function(a,b){if(0!=this.g&&(this.Ub==a||this.Ed==a))if(this.Ne=a.Uj,this.Ed==a&&3==this.g)if(7<this.Og){try{var c=this.u.parse(b)}catch(f){c=null}if(g.Ka(c)&&3==c.length)if(0==c[0])a:{if(!this.qf){if(this.Ub)if(this.Ub.Gi+3E3<this.Ed.Gi)l4(this),this.Ub.cancel(),this.Ub=null;else break a;s4(this);I3(19)}}else this.nx=c[1],0<this.nx-this.ji&&37500>c[2]&&this.Ko&&0==this.Jh&&!this.Sg&&(this.Sg=S3((0,g.x)(this.yI,this),6E3));else u4(this,11)}else b!=Vqa.yO.g&&u4(this,11);else if(this.Ub==a&&
l4(this),!g.wb(b)){c=this.u.parse(b);g.Ka(c);for(var d=0;d<c.length;d++){var e=c[d];this.ji=e[0];e=e[1];2==this.g?"c"==e[0]?(this.l=e[1],this.Dm=e[2],e=e[3],null!=e?this.Og=e:this.Og=6,this.g=3,this.Vc&&this.Vc.ev(),this.Qu=Y3(this,this.Vk()?this.Dm:null,this.Aq),q4(this)):"stop"==e[0]&&u4(this,7):3==this.g&&("stop"==e[0]?u4(this,7):"noop"!=e[0]&&this.Vc&&this.Vc.dv(e),this.Jh=0)}}};
g.h.yI=function(){null!=this.Sg&&(this.Sg=null,this.Ub.cancel(),this.Ub=null,s4(this),I3(20))};
g.h.On=function(a){if(this.Ub==a){l4(this);this.Ub=null;var b=2}else if(this.Ed==a)this.Ed=null,b=1;else return;this.Ne=a.Uj;if(0!=this.g)if(a.Fe)1==b?(b=(0,g.D)()-a.Gi,v4.dispatchEvent(new d4(v4,a.qh?a.qh.length:0,b,this.Qh)),j4(this),this.o.length=0):q4(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.Ne)){if(d=1==b)this.Ed||this.og||1==this.g||2<=this.Qh?d=!1:(this.og=S3((0,g.x)(this.Bz,this,a),r4(this,this.Qh)),this.Qh++,d=!0);d=!(d||2==b&&s4(this))}if(d)switch(c){case 1:u4(this,
5);break;case 4:u4(this,10);break;case 3:u4(this,6);break;case 7:u4(this,12);break;default:u4(this,2)}}};
g.h.eD=function(a){if(!g.$a(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.ZM=function(a){a?I3(2):(I3(1),t4(this,8))};
g.h.Vp=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new R2;a.T=!1;return a};
g.h.isActive=function(){return!!this.Vc&&this.Vc.isActive(this)};
g.h.Ce=function(a){v4.dispatchEvent(new e4(v4,a))};
g.h.Vk=function(){return!(!g.Ld||g.md(10))};
g.h=w4.prototype;g.h.ev=function(){};
g.h.dv=function(){};
g.h.cv=function(){};
g.h.Jp=function(){};
g.h.bw=function(){return{}};
g.h.isActive=function(){return!0};g.Sa(x4,g.A);g.h=x4.prototype;g.h.AL=function(){this.Yc=Math.min(3E5,2*this.Yc);this.l();this.i&&this.start()};
g.h.start=function(){var a=this.Yc+15E3*Math.random();g.Do(this.g,a);this.i=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.i=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Yc=5E3};g.Sa(y4,w4);g.h=y4.prototype;g.h.subscribe=function(a,b,c){return this.l.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.l.unsubscribe(a,b,c)};
g.h.Lf=function(a){return this.l.Yg(a)};
g.h.N=function(a,b){return this.l.N.apply(this.l,arguments)};
g.h.dispose=function(){this.ib||(this.ib=!0,g.qf(this.l),z4(this),g.qf(this.i),this.i=null)};
g.h.fa=function(){return this.ib};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.F="";this.i.stop();this.u=a||null;this.o=b||0;a=this.H+"/test";b=this.H+"/bind";var d=new b4(c?c.firstTestResults:null,c?c.secondTestResults:null,this.I),e=this.g;e&&(e.Vc=null);d.Vc=this;this.g=d;e?this.g.connect(a,b,this.A,e.l,e.ji):c?this.g.connect(a,b,this.A,c.sessionId,c.arrayId):this.g.connect(a,b,this.A)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.ec(c,b);this.i.isActive()||2==(this.g?this.g.g:0)?this.B.push(c):A4(this)&&m4(this.g,c)};
g.h.ev=function(){this.i.reset();this.u=null;this.o=0;if(this.B.length){var a=this.B;this.B=[];for(var b=0,c=a.length;b<c;++b)m4(this.g,a[b])}this.N("handlerOpened")};
g.h.cv=function(a){var b=2==a&&401==this.g.Ne;4==a||b||this.i.start();this.N("handlerError",a)};
g.h.Jp=function(a){if(!this.i.isActive())this.N("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.B.push(d)}};
g.h.bw=function(){var a={v:2};this.F&&(a.gsessionid=this.F);0!=this.o&&(a.ui=""+this.o);0!=this.D&&(a.ui=""+this.D);this.u&&g.ec(a,this.u);return a};
g.h.dv=function(a){"S"==a[0]?this.F=a[1]:"gracefulReconnect"==a[0]?(this.i.start(),i4(this.g)):this.N("handlerMessage",new mqa(a[0],a[1]))};
g.h.DM=function(){this.i.isActive();var a=this.g,b=0;a.Ub&&b++;a.Ed&&b++;0==b&&this.connect(this.u,this.o)};B4.prototype.o=function(a,b,c,d){b?a(d):a({text:c.responseText})};
B4.prototype.l=function(a,b){a(Error("Request error: "+b.status))};
B4.prototype.u=function(a){a(Error("request timed out"))};var sqa=(0,g.D)(),G4=null,K4=Array(50),J4=-1,L4=!1;g.Sa(M4,g.N);M4.prototype.Qd=function(){return this.g};
M4.prototype.contains=function(a){return!!g3(this.g,a)};
M4.prototype.get=function(a){return a?h3(this.g,a):null};
M4.prototype.info=function(a){I4(this.B,a)};g.t(O4,g.N);g.h=O4.prototype;g.h.start=function(){!this.g&&isNaN(this.Aa)&&this.FB()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);isNaN(this.Aa)||(g.gq(this.Aa),this.Aa=NaN)};
g.h.U=function(){this.stop();g.N.prototype.U.call(this)};
g.h.FB=function(){this.Aa=NaN;this.g=g.br(C4(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:this.u},timeout:5E3,onSuccess:(0,g.x)(this.AN,this),onError:(0,g.x)(this.zN,this),oe:(0,g.x)(this.BN,this)})};
g.h.AN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.l;c.name=this.o;this.N("pairingComplete",new $2(c))};
g.h.zN=function(a){this.g=null;a.status&&404==a.status?this.i>=X6.length?this.N("pairingFailed",Error("DIAL polling timed out")):(a=X6[this.i],this.Aa=g.eq((0,g.x)(this.FB,this),a),this.i++):this.N("pairingFailed",Error("Server error "+a.status))};
g.h.BN=function(){this.g=null;this.N("pairingFailed",Error("Server not responding"))};
var X6=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Sa(Q4,M4);g.h=Q4.prototype;g.h.start=function(){P4(this)&&this.N("screenChange");!g.It("yt-remote-lounge-token-expiration")&&R4(this);g.gq(this.i);this.i=g.eq((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){P4(this);N4(this,a);S4(this,!1);this.N("screenChange");b(a);a.token||R4(this)};
g.h.remove=function(a,b){var c=P4(this);uqa(this,a)&&(S4(this,!1),c=!0);b(a);c&&this.N("screenChange")};
g.h.Go=function(a,b,c,d){var e=P4(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,S4(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.N("screenChange")};
g.h.U=function(){g.gq(this.i);Q4.ab.U.call(this)};
g.h.OD=function(a){P4(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}S4(this,!b);b&&I4(this.B,"Missed "+b+" lounge tokens.")};
g.h.ND=function(a){I4(this.B,"Requesting lounge tokens failed: "+a)};g.t(U4,g.N);g.h=U4.prototype;g.h.start=function(){var a=parseInt(g.It("yt-remote-fast-check-period")||"0",10);(this.o=(0,g.D)()-144E5<a?0:a)?X4(this):(this.o=(0,g.D)()+3E5,g.Ht("yt-remote-fast-check-period",this.o),this.Ns())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){T4("Updating availability on schedule.");var a=this.A(),b=g.Lb(this.g,function(c,d){return c&&!!h3(a,d)},this);
W4(this,b)};
g.h.U=function(){g.gq(this.l);this.l=NaN;this.i&&(this.i.abort(),this.i=null);g.N.prototype.U.call(this)};
g.h.Ns=function(){g.gq(this.l);this.l=NaN;this.i&&this.i.abort();var a=Y4(this);if(U2(a)){var b=C4(this.u,"/pairing/get_screen_availability");this.i=D4(this.u,b,{lounge_token:g.Rb(a).join(",")},(0,g.x)(this.dL,this,a),(0,g.x)(this.cL,this))}else W4(this,{}),X4(this)};
g.h.dL=function(a,b){this.i=null;var c=g.Rb(Y4(this));if(g.rb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;W4(this,d);X4(this)}else this.Gb("Changing Screen set during request."),this.Ns()};
g.h.cL=function(a){this.Gb("Screen availability failed: "+a);this.i=null;X4(this)};
g.h.Gb=function(a){I4("OnlineScreenService",a)};g.Sa(Z4,M4);g.h=Z4.prototype;g.h.start=function(){this.l.start();this.i.start();this.g.length&&(this.N("screenChange"),this.i.isEmpty()||this.N("onlineScreenChange"))};
g.h.add=function(a,b,c){this.l.add(a,b,c)};
g.h.remove=function(a,b,c){this.l.remove(a,b,c);this.i.update()};
g.h.Go=function(a,b,c,d){this.l.contains(a)?this.l.Go(a,b,c,d):(a="Updating name of unknown screen: "+a.name,I4(this.B,a),d(Error(a)))};
g.h.Qd=function(a){return a?this.g:g.fb(this.g,(0,g.Xd)(this.o,function(b){return!this.contains(b)},this))};
g.h.GB=function(){return(0,g.Xd)(this.Qd(!0),function(a){return!!this.i.g[a.id]},this)};
g.h.HB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new O4(this.A,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.qf(f);d($4(this,k))},this));
f.subscribe("pairingFailed",function(k){g.qf(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.DN=function(a,b,c,d){g.br(C4(this.A,"/pairing/get_screen"),{method:"POST",wb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new $2(f.screen||{});if(!k.name||b5(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);b5(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c($4(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
oe:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.qf(this.l);g.qf(this.i);Z4.ab.U.call(this)};
g.h.WD=function(){c5(this);this.N("screenChange");this.i.update()};
Z4.prototype.dispose=Z4.prototype.dispose;g.Sa(e5,g.N);g.h=e5.prototype;g.h.Qn=function(a){this.l=a;this.N("sessionScreen",this.l)};
g.h.Td=function(a){this.fa()||(a&&f5(this,""+a),this.l=null,this.N("sessionScreen",null))};
g.h.info=function(a){I4(this.R,a)};
g.h.JB=function(){return null};
g.h.Ws=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){f5(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Ws("");e5.ab.U.call(this)};g.Sa(h5,e5);g.h=h5.prototype;g.h.Vs=function(a){if(this.g){if(this.g==a)return;f5(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.A);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u)}this.g=a;this.g.addUpdateListener(this.A);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.u);yqa(this)};
g.h.li=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.x)(function(){this.Td()},this),(0,g.x)(function(){this.Td(Error("Failed to stop receiver app."))},this)):this.Td(Error("Stopping cast device witout session."))};
g.h.Ws=g.Ha;g.h.U=function(){this.info("disposeInternal");g.gq(this.o);this.o=0;this.g&&(this.g.removeUpdateListener(this.A),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.u));this.g=null;h5.ab.U.call(this)};
g.h.dM=function(a,b){if(!this.fa())if(b){var c=W2(b);if(g.Na(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":g5(this,c.screenId);break;default:f5(this,"Unknown youtube message: "+d)}}else f5(this,"Unable to parse message.")}else f5(this,"No data in message.")};
g.h.tw=function(a,b,c,d){a5(this.F,this.i.label,a,this.i.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(f5(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.eq((0,g.x)(this.tw,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.JB=function(){return this.g};
g.h.EN=function(a){this.fa()||a||(f5(this,"Cast session died."),this.Td())};g.Sa(i5,e5);g.h=i5.prototype;g.h.Vs=function(a){this.o=a;this.o.addUpdateListener(this.I)};
g.h.li=function(a){this.u=a;this.B()};
g.h.stop=function(){this.g();this.g=g.Ha;g.gq(this.A);this.o?this.o.stop((0,g.x)(this.Td,this,null),(0,g.x)(this.Td,this,"Failed to stop DIAL device.")):this.Td()};
g.h.U=function(){this.g();this.g=g.Ha;g.gq(this.A);this.o&&this.o.removeUpdateListener(this.I);this.o=null;i5.ab.U.call(this)};
g.h.HN=function(a){this.fa()||a||(f5(this,"DIAL session died."),this.g(),this.g=g.Ha,this.Td())};
g.h.Pq=function(a){this.H=f3();if(this.u){var b=new chrome.cast.DialLaunchResponse(!0,k5(this));a(b);j5(this)}else this.B=(0,g.x)(function(){g.gq(this.A);this.B=g.Ha;this.A=NaN;var c=new chrome.cast.DialLaunchResponse(!0,k5(this));a(c);j5(this)},this),this.A=g.eq((0,g.x)(function(){this.B()},this),100)};
g.h.rE=function(a,b,c){a5(this.F,this.D.receiver.label,a,this.i.friendlyName,(0,g.x)(function(d){d&&d.token?(this.Qn(d),b(new chrome.cast.DialLaunchResponse(!1))):this.Pq(b,c)},this),(0,g.x)(function(d){f5(this,"Failed to get DIAL screen: "+d);
this.Pq(b,c)},this))};g.Sa(l5,e5);l5.prototype.stop=function(){this.Td()};
l5.prototype.Vs=g.Ha;l5.prototype.li=function(){g.gq(this.g);this.g=NaN;var a=h3(this.F.Qd(),this.i.label);a?this.Qn(a):this.Td(Error("No such screen"))};
l5.prototype.U=function(){g.gq(this.g);this.g=NaN;l5.ab.U.call(this)};g.Sa(m5,g.N);g.h=m5.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.B);this.D||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.MK,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.yz,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.aJ,this);chrome.cast.initialize(c,(0,g.x)(function(){this.fa()||
(chrome.cast.addReceiverActionListener(this.o),pqa(),this.i.subscribe("onlineScreenChange",(0,g.x)(this.IB,this)),this.l=r5(this),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(k){this.Gb("Failed to set initial custom receivers: "+g.Kg(k))},this)),this.N("yt-remote-cast2-availability-change",p5(this)),b(!0))},this),(0,g.x)(function(k){this.Gb("Failed to initialize API: "+g.Kg(k));
b(!1)},this))};
g.h.MM=function(a,b){o5("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.l;if(!a||c&&c.id!=a)o5("Unsetting old screen status: "+this.g.i.friendlyName),q5(this,null)}if(a&&b){if(!this.g){c=h3(this.i.Qd(),a);if(!c){o5("setConnectedScreenStatus: Unknown screen.");return}var d=n5(this,c);d||(o5("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.l.push(d),chrome.cast.setCustomReceivers(this.l,
g.Ha,(0,g.x)(function(e){this.Gb("Failed to set initial custom receivers: "+g.Kg(e))},this)));
o5("setConnectedScreenStatus: new active receiver: "+d.friendlyName);q5(this,new l5(this.i,d),!0)}this.g.Ws(b)}else o5("setConnectedScreenStatus: no screen.")};
g.h.OM=function(a){this.fa()?this.Gb("Setting connection data on disposed cast v2"):this.g?this.g.li(a):this.Gb("Setting connection data without a session")};
g.h.GN=function(){this.fa()?this.Gb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),q5(this,null)):o5("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.yz,this),(0,g.x)(this.jL,this))};
g.h.U=function(){this.i.unsubscribe("onlineScreenChange",(0,g.x)(this.IB,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.o);g.db(g.w("yt.mdx.remote.debug.handlers_")||[],E4);g.qf(this.g);m5.ab.U.call(this)};
g.h.Gb=function(a){I4("Controller",a)};
g.h.zz=function(a,b){this.g==a&&(b||q5(this,null),this.N("yt-remote-cast2-session-change",b))};
g.h.IK=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),o5("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.i.label!=a.label)o5("onReceiverAction_: Stopping active receiver: "+this.g.i.friendlyName),this.g.stop();else{o5("onReceiverAction_: Casting to active receiver.");this.g.l&&this.N("yt-remote-cast2-session-change",this.g.l);break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:q5(this,
new l5(this.i,a));break;case chrome.cast.ReceiverType.DIAL:q5(this,new i5(this.i,a,this.A));break;case chrome.cast.ReceiverType.CAST:q5(this,new h5(this.i,a));break;default:this.Gb("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.g&&this.g.i.label==a.label?this.g.stop():this.Gb("Stopping receiver w/o session: "+a.friendlyName)}else this.Gb("onReceiverAction_ called without receiver.")};
g.h.aJ=function(a){if(this.fa())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.Gb("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.i:null;if(!c||c.label!=b.label)return this.Gb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.g.l)return o5("Reselecting dial screen."),
this.N("yt-remote-cast2-session-change",this.g.l),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.Gb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);q5(this,new i5(this.i,b,this.A))}b=this.g;b.D=a;return b.D.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.rE,b,(b.D.extraData||{}).screenId||null)):new Promise((0,g.x)(b.Pq,b))};
g.h.yz=function(a){if(!this.fa()){o5("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==chrome.cast.ReceiverType.CAST)o5("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),q5(this,new h5(this.i,b),!0);else{this.Gb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.i,d=h3(this.i.Qd(),c.label);d&&a3(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(o5("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.qf(this.g),this.g=new h5(this.i,b),this.g.subscribe("sessionScreen",(0,g.x)(this.zz,this,this.g)),this.g.li(null));this.g.Vs(a)}}};
g.h.FN=function(){return this.g?this.g.JB():null};
g.h.jL=function(a){this.fa()||(this.Gb("Failed to estabilish a session: "+g.Kg(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&q5(this,null))};
g.h.MK=function(a){o5("Receiver availability updated: "+a);if(!this.fa()){var b=p5(this);this.u=a==chrome.cast.ReceiverAvailability.AVAILABLE;p5(this)!=b&&this.N("yt-remote-cast2-availability-change",p5(this))}};
g.h.IB=function(){this.fa()||(this.l=r5(this),o5("Updating custom receivers: "+g.Kg(this.l)),chrome.cast.setCustomReceivers(this.l,g.Ha,(0,g.x)(function(){this.Gb("Failed to set custom receivers.")},this)),this.N("yt-remote-cast2-availability-change",p5(this)))};
m5.prototype.setLaunchParams=m5.prototype.OM;m5.prototype.setConnectedScreenStatus=m5.prototype.MM;m5.prototype.stopSession=m5.prototype.GN;m5.prototype.getCastSession=m5.prototype.FN;m5.prototype.requestSession=m5.prototype.requestSession;m5.prototype.init=m5.prototype.init;m5.prototype.dispose=m5.prototype.dispose;var A5=[];I5.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";J5(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Oe=a.hasPrevious,this.hasNext=a.hasNext,this.B=a.playerTime,this.A=a.playerTimeAt,this.o=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.F=a.loadedTime,this.l=a.liveIngestionTime,this.u=
!isNaN(this.l))};
I5.prototype.isAdPlaying=function(){return 1081==this.playerState};
I5.prototype.getDuration=function(){return this.u?this.D+K5(this):this.D};
I5.prototype.clone=function(){return new I5(O5(this))};g.t(R5,g.N);g.h=R5.prototype;g.h.play=function(){1==this.g?(this.i?this.i.play(null,g.Ha,Z5(this,"play")):X5(this,"play"),W5(this,1,M5(S5(this))),this.N("remotePlayerChange")):U5(this,this.play)};
g.h.pause=function(){1==this.g?(this.i?this.i.pause(null,g.Ha,Z5(this,"pause")):X5(this,"pause"),W5(this,2,M5(S5(this))),this.N("remotePlayerChange")):U5(this,this.pause)};
g.h.seekTo=function(a){if(1==this.g){if(this.i){var b=S5(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?chrome.cast.media.ResumeState.PLAYBACK_START:chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,Z5(this,"seekTo",{newTime:a}))}else X5(this,"seekTo",{newTime:a});W5(this,3,a);this.N("remotePlayerChange")}else U5(this,g.Qa(this.seekTo,a))};
g.h.stop=function(){if(1==this.g){this.i?this.i.stop(null,g.Ha,Z5(this,"stopVideo")):X5(this,"stopVideo");var a=S5(this);a.index=-1;a.videoId="";J5(a);V5(this,a);this.N("remotePlayerChange")}else U5(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=S5(this);if(this.l){if(c.volume!=a){var d=Math.round(a)/100;this.l.setReceiverVolumeLevel(d,(0,g.x)(function(){I4("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.Gb("failed to set receiver volume.")},this))}c.muted!=b&&this.l.setReceiverMuted(b,(0,g.x)(function(){I4("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.Gb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);X5(this,"setVolume",e)}c.muted=b;c.volume=a;V5(this,c)}else U5(this,g.Qa(this.setVolume,a,b))};
g.h.JA=function(a,b){if(1==this.g){var c=S5(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Kg(b.style),g.ec(d,c.g));X5(this,"setSubtitlesTrack",d);V5(this,c)}else U5(this,g.Qa(this.JA,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.g){var c=b.getLanguageInfo().getId();X5(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=S5(this);d.audioTrackId=c;V5(this,d)}else U5(this,g.Qa(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=S5(this);c=c||0;var m={videoId:a,currentIndex:c};N5(l,a,c);g.Ca(b)&&(L5(l,b),m.currentTime=b);g.Ca(d)&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Kg(k));X5(this,"setPlaylist",m);d||V5(this,l)};
g.h.Xn=function(a,b){if(1==this.g){if(a&&b){var c=S5(this);N5(c,a,b);V5(this,c)}X5(this,"previous")}else U5(this,g.Qa(this.Xn,a,b))};
g.h.nextVideo=function(a,b){if(1==this.g){if(a&&b){var c=S5(this);N5(c,a,b);V5(this,c)}X5(this,"next")}else U5(this,g.Qa(this.nextVideo,a,b))};
g.h.Iv=function(){1==this.g?X5(this,"dismissAutoplay"):U5(this,this.Iv)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.N("proxyStateChange",a,this.g)}g.N.prototype.dispose.call(this)};
g.h.U=function(){T5(this);this.o=null;this.u.clear();Q5(this,null);g.N.prototype.U.call(this)};
g.h.Mt=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.N("proxyStateChange",b,a);if(1==a)for(;!this.u.isEmpty();)b=a=this.u,0==b.g.length&&(b.g=b.i,b.g.reverse(),b.i=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.FK=function(a,b){this.N(a,b)};
g.h.FI=function(a){if(!a)this.Ek(null),Q5(this,null);else if(this.l.receiver.volume){a=this.l.receiver.volume;var b=S5(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)I4("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,V5(this,b)}};
g.h.Ek=function(a){I4("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.D);if(this.i=a)this.i.addUpdateListener(this.D),Y5(this),this.N("remotePlayerChange")};
g.h.DI=function(a){a?(Y5(this),this.N("remotePlayerChange")):this.Ek(null)};
g.h.vt=function(){X5(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.TI=function(){var a=E5();a&&Q5(this,a)};
g.h.Gb=function(a){I4("CP",a)};g.t($5,g.N);g.h=$5.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.Ca(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.Ca(k)&&(l.currentIndex=k);c&&(this.Pa.listId=c);this.Pa.videoId=d;this.Pa.index=k||0;this.Pa.state=3;L5(this.Pa,m);this.o="UNSUPPORTED";a6("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",
params:g.Kg(l)},a,o3())}else a6("Connecting without params"),this.g.connect({},a,o3());Fqa(this)};
g.h.dispose=function(){this.fa()||(this.N("beforeDispose"),b6(this,3));g.N.prototype.dispose.call(this)};
g.h.U=function(){c6(this);e6(this);d6(this);g.gq(this.B);this.B=NaN;g.gq(this.D);this.D=NaN;this.l=null;g.ls(this.R);this.R.length=0;this.g.dispose();g.N.prototype.U.call(this);this.o=this.A=this.i=this.Pa=this.g=null};
g.h.HD=function(){this.Nh(2)};
g.h.JI=function(){a6("Channel opened");this.I&&(this.I=!1,d6(this),this.H=g.eq((0,g.x)(function(){a6("Timing out waiting for a screen.");this.Nh(1)},this),15E3));
gqa(nqa(this.g),this.M)};
g.h.GI=function(){a6("Channel closed");isNaN(this.u)?r3(!0):r3();this.dispose()};
g.h.HI=function(a){r3();isNaN(this.Jj())?(a6("Channel error: "+a+" without reconnection"),this.dispose()):(this.I=!0,a6("Channel error: "+a+" with reconnection in "+this.Jj()+" ms"),b6(this,2))};
g.h.II=function(a){a.params?a6("Received: action="+a.action+", params="+g.Kg(a.params)):a6("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=W2(a.params.devices);this.i=(0,g.ge)(a,function(c){return new Z2(c)});
a=!!g.Xa(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
h6(this,a);break;case "loungeScreenDisconnected":g.eb(this.i,function(c){return"LOUNGE_SCREEN"==c.type});
h6(this,!1);break;case "remoteConnected":var b=new Z2(W2(a.params.device));g.Xa(this.i,function(c){return b?c.id==b.id:!1})||Wpa(this.i,b);
break;case "remoteDisconnected":b=new Z2(W2(a.params.device));g.eb(this.i,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":i6(this,a);break;case "nowPlaying":Iqa(this,a);break;case "onStateChange":j6(this,a);break;case "onAdStateChange":Jqa(this,a);break;case "onVolumeChanged":Kqa(this,a);break;case "onSubtitlesTrackChanged":Hqa(this,a);break;case "nowAutoplaying":Lqa(this,a);break;case "autoplayDismissed":this.N("autoplayDismissed");break;case "autoplayUpNext":this.A=a.params.videoId||null;this.N("autoplayUpNext",this.A);break;case "onAutoplayModeChanged":this.o=
a.params.autoplayMode;this.N("autoplayModeChange",this.o);"DISABLED"==this.o&&this.N("autoplayDismissed");break;case "onHasPreviousNextChanged":Mqa(this,a);break;case "requestAssistedSignIn":this.N("assistedSignInRequested",a.params.authCode);break;default:a6("Unrecognized action: "+a.action)}};
g.h.AM=function(){if(this.l){var a=this.l;this.l=null;this.Pa.videoId!=a&&f6(this,"getNowPlaying")}};
g.h.xD=function(){var a=3;this.fa()||(a=0,isNaN(this.Jj())?A4(this.g)&&isNaN(this.u)&&(a=1):a=2);return a};
g.h.Nh=function(a){a6("Disconnecting with "+a);c6(this);this.N("beforeDisconnect",a);1==a&&r3();z4(this.g,a);this.dispose()};
g.h.wD=function(){var a=this.Pa;this.l&&(a=this.Pa.clone(),N5(a,this.l,a.index));return O5(a)};
g.h.PM=function(a){var b=new I5(a);b.videoId&&b.videoId!=this.Pa.videoId&&(this.l=b.videoId,g.gq(this.B),this.B=g.eq((0,g.x)(this.AM,this),5E3));var c=[];this.Pa.listId==b.listId&&this.Pa.videoId==b.videoId&&this.Pa.index==b.index||c.push("remoteQueueChange");this.Pa.playerState==b.playerState&&this.Pa.volume==b.volume&&this.Pa.muted==b.muted&&M5(this.Pa)==M5(b)&&g.Kg(this.Pa.g)==g.Kg(b.g)||c.push("remotePlayerChange");this.Pa.reset(a);(0,g.y)(c,function(d){this.N(d)},this)};
g.h.qw=function(){var a=this.g.A.id,b=g.Xa(this.i,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.Jj=function(){var a=this.g;return a.i.isActive()?a.i.i-(0,g.D)():NaN};
g.h.pD=function(){return this.o||"UNSUPPORTED"};
g.h.qD=function(){return this.A||""};
g.h.yN=function(){if(!isNaN(this.Jj())){var a=this.g.i;g.Eo(a.g);a.start()}};
g.h.HM=function(a,b){f6(this,a,b);g6(this)};
$5.prototype.subscribe=$5.prototype.subscribe;$5.prototype.unsubscribeByKey=$5.prototype.Lf;$5.prototype.getProxyState=$5.prototype.xD;$5.prototype.disconnect=$5.prototype.Nh;$5.prototype.getPlayerContextData=$5.prototype.wD;$5.prototype.setPlayerContextData=$5.prototype.PM;$5.prototype.getOtherConnectedRemoteId=$5.prototype.qw;$5.prototype.getReconnectTimeout=$5.prototype.Jj;$5.prototype.getAutoplayMode=$5.prototype.pD;$5.prototype.getAutoplayVideoId=$5.prototype.qD;$5.prototype.reconnect=$5.prototype.yN;
$5.prototype.sendMessage=$5.prototype.HM;g.t(k6,M4);g.h=k6.prototype;g.h.Qd=function(a){return this.Xc.$_gs(a)};
g.h.contains=function(a){return!!this.Xc.$_c(a)};
g.h.get=function(a){return this.Xc.$_g(a)};
g.h.start=function(){this.Xc.$_st()};
g.h.add=function(a,b,c){this.Xc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Xc.$_r(a,b,c)};
g.h.Go=function(a,b,c,d){this.Xc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.i.length;a<b;++a)this.Xc.$_ubk(this.i[a]);this.i.length=0;this.Xc=null;M4.prototype.U.call(this)};
g.h.CN=function(){this.N("screenChange")};
g.h.kK=function(){this.N("onlineScreenChange")};
Z4.prototype.$_st=Z4.prototype.start;Z4.prototype.$_gspc=Z4.prototype.DN;Z4.prototype.$_gsppc=Z4.prototype.HB;Z4.prototype.$_c=Z4.prototype.contains;Z4.prototype.$_g=Z4.prototype.get;Z4.prototype.$_a=Z4.prototype.add;Z4.prototype.$_un=Z4.prototype.Go;Z4.prototype.$_r=Z4.prototype.remove;Z4.prototype.$_gs=Z4.prototype.Qd;Z4.prototype.$_gos=Z4.prototype.GB;Z4.prototype.$_s=Z4.prototype.subscribe;Z4.prototype.$_ubk=Z4.prototype.Lf;var G6=null,F6=!1,l6=null,m6=null,C6=null,q6=[];g.t(H6,g.A);g.h=H6.prototype;
g.h.U=function(){g.A.prototype.U.call(this);this.o.stop();this.A.stop();this.I.stop();this.M();this.g.unsubscribe("proxyStateChange",this.vz,this);this.g.unsubscribe("remotePlayerChange",this.Gk,this);this.g.unsubscribe("remoteQueueChange",this.Rn,this);this.g.unsubscribe("autoplayUpNext",this.Wy,this);this.g.unsubscribe("previousNextChange",this.rz,this);this.g.unsubscribe("nowAutoplaying",this.nz,this);this.g.unsubscribe("autoplayDismissed",this.Vy,this);this.g=this.u=null};
g.h.Tx=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(L6(this)){if(!S5(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==S5(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.H.Qj(c[0],c[1]);break;case "control_subtitles_set_track":M6(this,c[0]);break;case "control_set_audio_track":c=c[0],L6(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.i.getCurrentTime();N6(this,0==c?void 0:c);break;case "control_seek":N6(this,c[0]);break;case "control_subtitles_set_track":M6(this,c[0]);break;case "control_set_audio_track":c=c[0],L6(this)&&this.g.setAudioTrack(this.i.getVideoData(1).videoId,c)}};
g.h.CI=function(a){this.I.DD(a)};
g.h.iN=function(a){this.Tx("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.UA=function(){var a=this.i.getOption("captions","track");g.Xb(a)||M6(this,a)};
g.h.iz=function(a){if(L6(this)){this.g.unsubscribe("remotePlayerChange",this.Gk,this);var b=Math.round(a.volume);a=!!a.muted;var c=S5(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.R.start();this.g.subscribe("remotePlayerChange",this.Gk,this)}};
g.h.FJ=function(){g.Xb(this.B)||O6(this,this.B);this.D=!1};
g.h.vz=function(a,b){this.A.stop();2==b&&this.TA()};
g.h.Gk=function(){if(L6(this)){this.o.stop();var a=S5(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.Um=1;break;case 1082:case 1083:this.u.Um=0;break;default:this.u.Um=-1}switch(a.playerState){case 1081:case 1:J6(this,new g.OC(8));this.SA();break;case 1085:case 3:J6(this,new g.OC(9));break;case 1083:case 0:J6(this,new g.OC(2));this.H.stop();I6(this,this.i.getVideoData().lengthSeconds);break;case 1084:J6(this,new g.OC(4));break;case 2:J6(this,new g.OC(4));I6(this,M5(a));
break;case -1:J6(this,new g.OC(64));break;case -1E3:J6(this,new g.OC(128,{errorCode:"mdx.remoteerror",errorMessage:"Dieses Video ist nicht f\u00fcr die Remote-Wiedergabe verf\u00fcgbar."}))}a=S5(this.g).g;var b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.B=a,O6(this,a));a=S5(this.g);-1==a.volume||Math.round(this.i.getVolume())==a.volume&&this.i.isMuted()==a.muted||this.R.isActive()||this.uB()}else K6(this)};
g.h.rz=function(){this.i.N("mdxpreviousnextchange")};
g.h.Rn=function(){L6(this)||K6(this)};
g.h.KC=function(){this.g.Iv()};
g.h.Wy=function(a){a&&(a=g.br("/watch_queue_ajax",{method:"GET",ud:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.x)(this.LL,this)}))&&(this.M=(0,g.x)(a.abort,a))};
g.h.LL=function(a,b){var c=new g.yB(g.X(this.i),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.i.N("mdxautoplayupnext",c)};
g.h.nz=function(a){isNaN(a)||this.i.N("mdxnowautoplaying",a)};
g.h.Vy=function(){this.i.N("mdxautoplaycanceled")};
g.h.cG=function(a,b){-1==S5(this.g).playerState?N6(this,a):b&&this.g.seekTo(a)};
g.h.uB=function(){if(L6(this)){var a=S5(this.g);this.l.Qa(this.P);a.muted?this.i.mute():this.i.unMute();this.i.setVolume(a.volume);this.P=this.l.K(this.i,"onVolumeChange",this.iz)}};
g.h.SA=function(){this.o.stop();if(!this.g.fa()){var a=S5(this.g);1==a.playerState&&J6(this,new g.OC(8));I6(this,M5(a));this.o.start()}};
g.h.TA=function(){this.A.stop();this.o.stop();var a=this.g.o.getReconnectTimeout();2==this.g.g&&!isNaN(a)&&this.A.start()};g.t(Q6,g.V);Q6.prototype.o=function(){Y2("mdx-privacy-popup-cancel");this.l.hide()};
Q6.prototype.A=function(){Y2("mdx-privacy-popup-confirm");this.l.hide()};g.t(S6,g.V);S6.prototype.u=function(a){R6(this,a.state)};g.t(T6,g.bT);T6.prototype.I=function(){var a=this.l.getOption("remote","receivers");a&&1<a.length&&!this.l.getOption("remote","quickCast")?(this.B=g.tb(a,this.A,this),g.dT(this,(0,g.ge)(a,this.A)),a=this.l.getOption("remote","currentReceiver"),this.me(this.A(a)),this.enable(!0)):this.enable(!1)};
T6.prototype.A=function(a){return a.key};
T6.prototype.Be=function(a){return"cast-selector-receiver"==a?"Streamen\u2026":this.B[a].name};
T6.prototype.Lc=function(a){g.bT.prototype.Lc.call(this,a);this.l.setOption("remote","currentReceiver",this.B[a]);this.o.ob()};g.t(U6,g.iL);g.h=U6.prototype;
g.h.create=function(){Rqa(g.ez(g.X(this.player)));this.o.push(g.lq("yt-remote-before-disconnect",this.zI,this));this.o.push(g.lq("yt-remote-connection-change",this.NK,this));this.o.push(g.lq("yt-remote-receiver-availability-change",this.sz,this));this.o.push(g.lq("yt-remote-auto-connect",this.LK,this));this.o.push(g.lq("yt-remote-receiver-resumed",this.KK,this));this.o.push(g.lq("mdx-privacy-popup-confirm",this.qM,this));this.o.push(g.lq("mdx-privacy-popup-cancel",this.pM,this));this.sz()};
g.h.load=function(){this.player.cancelPlayback();g.iL.prototype.load.call(this);this.u=new H6(this,this.player,this.g);var a=(a=E6())?a.currentTime:0;var b=B6()?new R5(w6(),void 0):null;0==a&&b&&(a=M5(S5(b)));0!=a&&this.td(a);P6(this,this.pk,this.pk);g.bV(this.player.app,6)};
g.h.unload=function(){this.player.N("mdxautoplaycanceled");this.l=this.i;g.rf(this.u,this.g);this.g=this.u=null;g.iL.prototype.unload.call(this);g.bV(this.player.app,5);V6(this)};
g.h.U=function(){g.mq(this.o);g.iL.prototype.U.call(this)};
g.h.af=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.u.Tx.apply(this.u,[a].concat(g.ea(c)))};
g.h.getAdState=function(){return this.Um};
g.h.zD=function(){return this.loaded?this.u.suggestion:null};
g.h.Oe=function(){return this.g?S5(this.g).Oe:!1};
g.h.hasNext=function(){return this.g?S5(this.g).hasNext:!1};
g.h.td=function(a,b){this.I=a||0;this.player.N("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.I};
g.h.getProgressState=function(){var a=S5(this.g),b=this.player.getVideoData();return{allowSeeking:g.O(g.X(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.ec():!a.isAdPlaying()&&this.player.ec(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.l+K5(a):a.l,isAtLiveHead:1>=(a.u?a.i+K5(a):a.i)-this.getCurrentTime(),loaded:a.F,seekableEnd:a.u?a.i+K5(a):a.i,seekableStart:0<a.o?a.o+
K5(a):a.o}};
g.h.nextVideo=function(){this.g&&this.g.nextVideo()};
g.h.Xn=function(){this.g&&this.g.Xn()};
g.h.zI=function(a){1==a&&(this.F=this.g?S5(this.g):null)};
g.h.NK=function(){var a=B6()?new R5(w6(),void 0):null;if(a){var b=this.l;this.loaded&&this.unload();this.g=a;this.F=null;b.key!=this.i.key&&(this.l=b,this.load())}else g.qf(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.F)&&a.videoId==this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M5(a)));this.player.N("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.sz=function(){this.B=[this.i].concat(Sqa());var a=x6()||this.i;W6(this,a);this.player.la("onMdxReceiversChange")};
g.h.kM=function(a){!this.D&&g.$D(a,8)&&(this.player.pauseVideo(),V6(this))};
g.h.LK=function(){var a=x6();W6(this,a)};
g.h.KK=function(){this.l=x6()};
g.h.qM=function(){this.D=!0;V6(this);F6=!1;G6&&z6(G6,1);G6=null};
g.h.pM=function(){this.D=!1;V6(this);W6(this,this.i);this.l=this.i;F6=!1;G6=null;this.player.playVideo()};
g.h.yc=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.B;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?G5():W6(this,b)),this.loaded?this.l:this.i;case "quickCast":return 2==this.B.length&&"cast-selector-receiver"==this.B[1].key?(b&&G5(),!0):!1}};
g.h.vt=function(){this.g.vt()};
g.h.Nb=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.vT.remote=U6;})(_yt_player);
